import joblib
import m2cgen as m2c

def generate_esp32_header():
    print("Loading updated model1_controller.joblib...")
    try:
        model = joblib.load("model1_controller.joblib")
    except FileNotFoundError:
        print("Error: Could not find model1_controller.joblib.")
        return

    print("Transpiling Random Forest AI into C code...")
    
    # Export the model to C. 
    # m2cgen automatically creates a function called `score` 
    c_code = m2c.export_to_c(model)
    
    # We will add a standard C++ header guard to make it safe for Arduino IDE
    header_content = f"""// EAT System - Tier 1 Process Controller
// Auto-generated by m2cgen for ESP32

#pragma once
#include <math.h>

{c_code}
"""

    print("Saving to model1_controller.h...")
    with open("model1_controller.h", "w") as f:
        f.write(header_content)
        
    print("Success! Your ESP32 edge controller brain is ready.")

if __name__ == "__main__":
    generate_esp32_header()